// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tourism.Models;

#nullable disable

namespace Tourism.Migrations
{
    [DbContext(typeof(TourismDbContext))]
    [Migration("20251109224230_init3")]
    partial class init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TourGuide", b =>
                {
                    b.Property<int>("TourGuideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourGuideId"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("creditCardCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("experienceYears")
                        .HasColumnType("int");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("languages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("pic")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("verificationDocuments")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("verified")
                        .HasColumnType("bit");

                    b.HasKey("TourGuideId");

                    b.HasIndex("creditCardCardNumber");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("TourGuides");
                });

            modelBuilder.Entity("Tourism.Models.Admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Tourism.Models.CreditCard", b =>
                {
                    b.Property<string>("CardNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardHolder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardNumber");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("Tourism.Models.Hotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creditCardCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("hotline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("pic")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("verificationDocuments")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("verified")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("creditCardCardNumber");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Tourism.Models.Meal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("accepted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("pic")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("restaurantId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("restaurantId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("Tourism.Models.Merchant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("creditCardCardNumber")
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("verificationDocuments")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("verified")
                        .HasColumnType("bit");

                    b.Property<string>("zipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("creditCardCardNumber");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("Tourism.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DeliversWithin")
                        .HasColumnType("int");

                    b.Property<bool>("accepted")
                        .HasColumnType("bit");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("count")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("merchantId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("offer")
                        .HasColumnType("float");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("merchantId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Tourism.Models.Relations.CartProduct", b =>
                {
                    b.Property<int>("TouristId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("TouristId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("Tourism.Models.Relations.FavouriteProduct", b =>
                {
                    b.Property<int>("touristId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.HasKey("touristId", "productId");

                    b.HasIndex("productId");

                    b.ToTable("FavouriteProducts");
                });

            modelBuilder.Entity("Tourism.Models.Relations.Image", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("imageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("serviceId")
                        .HasColumnType("int");

                    b.Property<string>("serviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Tourism.Models.Relations.InboxMsg", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("providerId")
                        .HasColumnType("int");

                    b.Property<string>("providerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("InboxMsgs");
                });

            modelBuilder.Entity("Tourism.Models.Relations.MerchantSocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("MerchantSocialMedias");
                });

            modelBuilder.Entity("Tourism.Models.Relations.ServiceRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("serviceId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("Tourism.Models.Relations.TouristFeedback", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<int>("targetId")
                        .HasColumnType("int");

                    b.Property<string>("targetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("touristId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("touristId");

                    b.ToTable("TouristFeedbacks");
                });

            modelBuilder.Entity("Tourism.Models.Relations.TouristProduct", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderId"));

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("arrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int>("touristId")
                        .HasColumnType("int");

                    b.HasKey("orderId");

                    b.HasIndex("productId");

                    b.HasIndex("touristId");

                    b.ToTable("TouristProducts");
                });

            modelBuilder.Entity("Tourism.Models.Relations.TouristRestaurant", b =>
                {
                    b.Property<int>("bookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookId"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("numberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("restaurant_id")
                        .HasColumnType("int");

                    b.Property<int>("restaurantid")
                        .HasColumnType("int");

                    b.Property<int>("tableNumber")
                        .HasColumnType("int");

                    b.Property<int>("touristId")
                        .HasColumnType("int");

                    b.HasKey("bookId");

                    b.HasIndex("restaurantid");

                    b.HasIndex("touristId");

                    b.ToTable("TouristRestaurants");
                });

            modelBuilder.Entity("Tourism.Models.Relations.TouristRoom", b =>
                {
                    b.Property<int>("bookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookId"));

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("numberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("roomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("touristId")
                        .HasColumnType("int");

                    b.HasKey("bookId");

                    b.HasIndex("roomId");

                    b.HasIndex("touristId");

                    b.ToTable("TouristRooms");
                });

            modelBuilder.Entity("Tourism.Models.Relations.TouristTrip", b =>
                {
                    b.Property<int>("bookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookId"));

                    b.Property<int>("touristId")
                        .HasColumnType("int");

                    b.Property<int>("tripId")
                        .HasColumnType("int");

                    b.HasKey("bookId");

                    b.HasIndex("touristId");

                    b.HasIndex("tripId");

                    b.ToTable("TouristTrips");
                });

            modelBuilder.Entity("Tourism.Models.Relations.VerificationRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("provider_Id")
                        .HasColumnType("int");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("VerificationRequests");
                });

            modelBuilder.Entity("Tourism.Models.Restaurant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creditCardCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("hotline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("pic")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("verificationDocuments")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("verified")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("creditCardCardNumber");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("Tourism.Models.Room", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("accepted")
                        .HasColumnType("bit");

                    b.Property<double>("cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("hotelId")
                        .HasColumnType("int");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numberOfMembers")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("hotelId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Tourism.Models.Table", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("accepted")
                        .HasColumnType("bit");

                    b.Property<double>("bookingPrice")
                        .HasColumnType("float");

                    b.Property<DateTime?>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("number")
                        .HasColumnType("int");

                    b.Property<int>("numberOfPersons")
                        .HasColumnType("int");

                    b.Property<int>("restaurant_id")
                        .HasColumnType("int");

                    b.Property<int>("restaurantid")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("restaurantid");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("Tourism.Models.Tourist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<decimal>("balance")
                        .HasMaxLength(40)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("email")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Tourists");
                });

            modelBuilder.Entity("Tourism.Models.Trip", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("accepted")
                        .HasColumnType("bit");

                    b.Property<double>("cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int>("tourGuideId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tourGuideId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TourGuide", b =>
                {
                    b.HasOne("Tourism.Models.CreditCard", "creditCard")
                        .WithMany()
                        .HasForeignKey("creditCardCardNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("creditCard");
                });

            modelBuilder.Entity("Tourism.Models.Hotel", b =>
                {
                    b.HasOne("Tourism.Models.CreditCard", "creditCard")
                        .WithMany()
                        .HasForeignKey("creditCardCardNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("creditCard");
                });

            modelBuilder.Entity("Tourism.Models.Meal", b =>
                {
                    b.HasOne("Tourism.Models.Restaurant", "restaurant")
                        .WithMany("meals")
                        .HasForeignKey("restaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("restaurant");
                });

            modelBuilder.Entity("Tourism.Models.Merchant", b =>
                {
                    b.HasOne("Tourism.Models.CreditCard", "creditCard")
                        .WithMany()
                        .HasForeignKey("creditCardCardNumber");

                    b.Navigation("creditCard");
                });

            modelBuilder.Entity("Tourism.Models.Product", b =>
                {
                    b.HasOne("Tourism.Models.Merchant", "merchant")
                        .WithMany("Products")
                        .HasForeignKey("merchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("merchant");
                });

            modelBuilder.Entity("Tourism.Models.Relations.CartProduct", b =>
                {
                    b.HasOne("Tourism.Models.Product", "Product")
                        .WithMany("cart")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourism.Models.Tourist", "Tourist")
                        .WithMany("cart")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("Tourism.Models.Relations.FavouriteProduct", b =>
                {
                    b.HasOne("Tourism.Models.Product", "product")
                        .WithMany("favourites")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourism.Models.Tourist", "tourist")
                        .WithMany("favourites")
                        .HasForeignKey("touristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("tourist");
                });

            modelBuilder.Entity("Tourism.Models.Relations.MerchantSocialMedia", b =>
                {
                    b.HasOne("Tourism.Models.Merchant", "Merchant")
                        .WithMany("SocialMediaLinks")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Tourism.Models.Relations.TouristFeedback", b =>
                {
                    b.HasOne("Tourism.Models.Tourist", "tourist")
                        .WithMany()
                        .HasForeignKey("touristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tourist");
                });

            modelBuilder.Entity("Tourism.Models.Relations.TouristProduct", b =>
                {
                    b.HasOne("Tourism.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourism.Models.Tourist", "tourist")
                        .WithMany()
                        .HasForeignKey("touristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("tourist");
                });

            modelBuilder.Entity("Tourism.Models.Relations.TouristRestaurant", b =>
                {
                    b.HasOne("Tourism.Models.Restaurant", "restaurant")
                        .WithMany()
                        .HasForeignKey("restaurantid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourism.Models.Tourist", "tourist")
                        .WithMany()
                        .HasForeignKey("touristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("restaurant");

                    b.Navigation("tourist");
                });

            modelBuilder.Entity("Tourism.Models.Relations.TouristRoom", b =>
                {
                    b.HasOne("Tourism.Models.Room", "room")
                        .WithMany()
                        .HasForeignKey("roomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourism.Models.Tourist", "tourist")
                        .WithMany()
                        .HasForeignKey("touristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("room");

                    b.Navigation("tourist");
                });

            modelBuilder.Entity("Tourism.Models.Relations.TouristTrip", b =>
                {
                    b.HasOne("Tourism.Models.Tourist", "tourist")
                        .WithMany()
                        .HasForeignKey("touristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourism.Models.Trip", "trip")
                        .WithMany()
                        .HasForeignKey("tripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tourist");

                    b.Navigation("trip");
                });

            modelBuilder.Entity("Tourism.Models.Restaurant", b =>
                {
                    b.HasOne("Tourism.Models.CreditCard", "creditCard")
                        .WithMany()
                        .HasForeignKey("creditCardCardNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("creditCard");
                });

            modelBuilder.Entity("Tourism.Models.Room", b =>
                {
                    b.HasOne("Tourism.Models.Hotel", "hotel")
                        .WithMany("rooms")
                        .HasForeignKey("hotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hotel");
                });

            modelBuilder.Entity("Tourism.Models.Table", b =>
                {
                    b.HasOne("Tourism.Models.Restaurant", "restaurant")
                        .WithMany("tables")
                        .HasForeignKey("restaurantid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("restaurant");
                });

            modelBuilder.Entity("Tourism.Models.Trip", b =>
                {
                    b.HasOne("TourGuide", "tourGuide")
                        .WithMany("trips")
                        .HasForeignKey("tourGuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tourGuide");
                });

            modelBuilder.Entity("TourGuide", b =>
                {
                    b.Navigation("trips");
                });

            modelBuilder.Entity("Tourism.Models.Hotel", b =>
                {
                    b.Navigation("rooms");
                });

            modelBuilder.Entity("Tourism.Models.Merchant", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SocialMediaLinks");
                });

            modelBuilder.Entity("Tourism.Models.Product", b =>
                {
                    b.Navigation("cart");

                    b.Navigation("favourites");
                });

            modelBuilder.Entity("Tourism.Models.Restaurant", b =>
                {
                    b.Navigation("meals");

                    b.Navigation("tables");
                });

            modelBuilder.Entity("Tourism.Models.Tourist", b =>
                {
                    b.Navigation("cart");

                    b.Navigation("favourites");
                });
#pragma warning restore 612, 618
        }
    }
}
